# Generated by Django 2.2.12 on 2021-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auto_20210625_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='DEFAULT NAME', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='txt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
