# Generated by Django 2.2.12 on 2021-06-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_auto_20210627_0156'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique file name'),
        ),
    ]
