# Generated by Django 2.2.12 on 2021-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_auto_20210627_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='txt_description',
            field=models.TextField(max_length=10000),
        ),
    ]
