# Generated by Django 2.2.12 on 2021-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_auto_20210629_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_pics'),
        ),
    ]
